language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://freddiecarre.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: sFjSi6/SwMxOREp2zVd/9wxuEgSKqQ0+qq1Cmd/EZPT2FTAkcpzs3uh6Z2BKNTonxUdpP9OBfgutRuYh5kP+yOiIpWG0qnx0AP89u3lpd0PxItEUHIO/HXeWwfpjcdDScudV94qkfuQ+8z5AtNPekXkTFGTS7kN2znkAtVk1xSvytCPHZdcj8JfzhzTod41mKnvQE2cLe4Erh0aQ5CRi26tnD6pBXeZefWEESxRKZn5ycMN77GoM/l0DvlEQLhuPLlZuj2fuV866nbjntP0nh8mCWUK4XDppnhldIS4w3U6MWX6ZhcU52YSyS3yRqQQ3E24a5vCqEOQRfu2cnWpaifZPOZLjOi2FhsqYIDkuFBKNm7DypxfkACaj/iJ1os/MYSfr8Zu5TUez1JOha0O2XCPOASdVW8Mf8h07h3KcIFWOozWkY6wXSRgrKHC/+TcUg2wLHDNrCJzDfJvbaYuaDqLeTaMmFNZE5mu1FsrhvuzQyDT58f6T2AM+oFaYXnmW0buTWSEpBnl3pMiC5heex2QJKtKa0H/orDBqnXCOv67ZIwcpp8/gYZOCIGLaNIa626C1AQru9c3ovsM5N5ouCI7lVvA0Q4YYCPt2O/KQSDAcwK4eFvE5cfra7bCbPOABnjTguzqmaOFgQIk3hpkk153grmqdRHZNyy/AHRZZTe4=
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
